### ISSUE TITLE
Can I use localstorage instead of cookie?

### ISSUE THREAD

**Issue by franky1017** [BitzArt/Blazor.Auth#15]
Is it possible to replace blazor.cookie as the underlying storage and use browser local storage instead? Or better yet, can you make this a configuration/setting to allow user to make a choice? Thanks!

**Comment by YuriyDurov** [comment]
Hello @franky1017, can you elaborate more on why you would want to use local storage and not cookies?

Also keep in mind that cookies allow using all authentication capabilities when both pre-rendering on server and rendering in static SSR, which local storage can not provide - due to the fact that when using these rendering environments, the rendering takes place on the server and not in the client's browser. So if you go with local storage, you can only do interactive rendering without prerendering, which is not ideal.

Cookies, unlike local storage, are available in all rendering environments.

**Comment by franky1017** [comment]
My web ui application calls another api application for all business logics. For the api call to work I need to send the jwt token generated by the authentication function. Currently I am storing this token in localstorage and then attach it to the http client for each call. 

Can I do the same with cookie?

**Comment by YuriyDurov** [comment]
@franky1017 Surely, this is an expected use case for this library. We have had some discussions on this topic [here](https://github.com/BitzArt/Blazor.Auth/issues/11#issuecomment-2135911954). Consider taking a look at that issue's discussion and do let me know if this answers your question.

**Comment by franky1017** [comment]
I read the discussion. So you are working on some changes at this time? Is it completed? Or should I use the workaround code in the discussion for now? Thanks again!

**Comment by YuriyDurov** [comment]
@franky1017 currently you can use all the methods suggested there. There are three methods:

1. Call `GetAuthenticationStateAsync` from `AuthenticationStateProvider`, get the Auth token from the returned object
2. Inject `ICookieService` and get the user's `AuthenticationToken` cookie
3. Use the Server part of your Blazor app as a reverse proxy to access your needed external API and have it get the Auth token from cookies and attach the JWT to the outbound part of the request.

Methods 1 and 2 are easier to implement, but they will become unavailable with the release of Blazor.Auth 1.0. Method 3 will remain functional after 1.0 is released.

We are working on something to make implementing the third method easier when using this library. Like some nice wrappers around YARP library or something in that neighborhood...

**Comment by franky1017** [comment]
Thanks for the info, can’t wait for the update!
